package JMenuBarForm;

import javax.swing.*;

public class JMenuBar {
    private JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private JMenu jmFile;
    private JMenuItem jiNew;
    private JMenuItem jiOpen;
    private JMenuItem jiRecentProject;
    private JMenuItem jiCloseProject;
    private JMenuItem jiSettings;
    private JMenuItem jiProjectStructure;
    private JMenuItem jiFileProperties;
    private JMenuItem jiLocalHistory;
    private JMenuItem jiSaveAll;
    private JMenuItem jiReloadAllfromDisl;
    private JMenuItem jiRepairIDE;
    private JMenuItem jiInvalidateCaches;
    private JMenuItem jiMenageIDESettings;
    private JMenuItem jiNewProjectsSetup;
    private JMenuItem jiSaveFileasTemplate;
    private JMenuItem jiExport;
    private JMenuItem jiPrint;
    private JMenuItem jiPowerSaveMode;
    private JMenuItem jiExit;
    private JMenu jmEdit;
    private JMenu jmView;
    private JMenu jmNavigate;
    private JMenu jmCode;
    private JMenu jmRefactor;
    private JMenu jmBuild;
    private JMenu jmRun;
    private JMenu jmTools;
    private JMenu jmGit;
    private JMenu jmWindow;
    private JMenu jmHelp;
    private JMenuItem jiUndo;
    private JMenuItem jiRedo;
    private JMenuItem jiCut;
    private JMenuItem jiCopy;
    private JMenuItem jiCopyasPlainText;
    private JMenuItem jiCopyPathReference;
    private JMenuItem jiPaste;
    private JMenuItem jiDelete;
    private JMenuItem jiFind;
    private JMenuItem jiFindUsages;
    private JSeparator s1;
    private JSeparator s2;
    private JSeparator s3;
    private JSeparator s4;
    private JSeparator s5;
    private JSeparator s6;
    private JSeparator s7;
    private JSeparator s8;
    private JSeparator s9;
    private JSeparator s10;
    private JMenuItem jiSelectAll;
    private JMenuItem jiAddCaretstoEndsofSelectedLines;
    private JMenuItem jiExtendSelection;
    private JMenuItem jiShrinkSelection;
    private JSeparator s11;
    private JMenuItem jiToggleCase;
    private JMenuItem jiJoinLines;
    private JMenuItem jiDuplicateLineorSelection;
    private JMenuItem jiFillParagraph;
    private JMenuItem jiSortLines;
    private JMenuItem jiReverseLines;
    private JMenuItem jiTranspose;
    private JSeparator s12;
    private JMenuItem jiIndentSelection;
    private JMenuItem jiUnindentLineorSelection;
    private JMenuItem jiConvertIndents;
    private JSeparator s13;
    private JMenuItem jiMacros;
    private JMenuItem jiBookmarks;
    private JSeparator s14;
    private JMenuItem jiEncodeXMLHTMLSpecialCharacters;
    private JMenuItem jiToolWindows;
    private JMenuItem jiAppearance;
    private JSeparator s15;
    private JMenuItem jiQuickDefinition;
    private JMenuItem jiShowSiblings;
    private JMenuItem jiQuickTypeDefinition;
    private JSeparator s16;
    private JMenuItem jiRecentFiles;
    private JMenuItem jiRecentlyChangedFiles;
    private JMenuItem jiRecentLocations;
    private JMenuItem jiRecentChhanges;
    private JSeparator s17;
    private JMenuItem jiCompareWith;
    private JSeparator s18;
    private JMenuItem jiQuickSwitchScheme;
    private JSeparator s19;
    private JMenuItem jiResetFontSize;
    private JSeparator s20;
    private JMenuItem jiBidiTextBaseDirection;
    private JMenuItem jiBack;
    private JMenuItem jiForward;
    private JSeparator s21;
    private JMenuItem jiSearchEverywhere;
    private JSeparator s22;
    private JMenuItem jiClass;
    private JMenuItem jiFile;
    private JMenuItem jiSymbol;
    private JSeparator s23;
    private JMenuItem jiNextHighlightedError;
    private JMenuItem jiPreviousHighlightedError;
    private JSeparator s24;
    private JMenuItem jiNextEmmetEditPoint;
    private JMenuItem jiPreviousEmmetEditPoint;
    private JMenuItem jiLastEditLocation;
    private JMenuItem jiNextEditLocation;
    private JSeparator s25;
    private JMenuItem jiNavigateInFile;
    private JSeparator s26;
    private JMenuItem jiSelectIn;
    private JMenuItem jiJumptoNavigationBar;
    private JSeparator s27;
    private JMenuItem jiDeclarationorUsages;
    private JMenuItem jiImplementations;
    private JMenuItem jiTypeDeclaration;
    private JMenuItem jiSuperMethod;
    private JMenuItem jiRelatedSymbol;
    private JSeparator s28;
    private JMenuItem jiFileStructure;
    private JMenuItem jiFilePath;
    private JMenuItem jiTypeHierarchy;
    private JMenuItem jiMethodHierarchy;
    private JMenuItem jiCallHierarchy;
    private JSeparator s29;
    private JMenuItem jiUptheStackTrace;
    private JMenuItem jiDowntheStackTrace;

    public static void main(String[] args) {
        JFrame frame = new JFrame("JMenuBar");
        frame.setContentPane(new JMenuBar().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
